version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - "3307:3306"
    networks:
      - default_bridge

  backend:
    container_name: backend
    image: ${SPRING_BOOT_IMAGE}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
    networks:
      default_bridge:
        ipv4_address: 172.16.1.5
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - build_folder:/var/www/frontend
    depends_on:
      - backend
    networks:
      - default_bridge

#  controller:
#    container_name: nGrinder_controller
#    image: ngrinder/controller:3.5.5
#    ports:
#      - "9000:80"
#      - "16001:16001"
#      - "12000-12009:12000-12009"
#    networks:
#      - default_bridge
#  agent:
#    container_name: nGrinder_agent
#    image: ngrinder/agent:3.5.5
#    links:
#      - controller
#    networks:
#      - default_bridge


networks:
  default_bridge:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24


volumes:
  build_folder: